### ISSUE TITLE
Weird error when flying

### ISSUE THREAD

**Issue by ant-7802** [LAX1DUDE/eaglercraft#102]
----------------------------------
  Line: 15823:393
  Type: TypeError
  Message: Failed to execute 'setPosition' on 'AudioListener': The provided float value is non-finite.
----------------------------------

TypeError: Failed to execute 'setPosition' on 'AudioListener': The provided float value is non-finite.
    at AudioListener.setPosition (<anonymous>)
    at API (https://g.eags.us/eaglercraft/classes11.js:1087:294)
    at AOv (https://g.eags.us/eaglercraft/classes11.js:1908:346)
    at A8O (https://g.eags.us/eaglercraft/classes11.js:1458:239)
    at Buo (https://g.eags.us/eaglercraft/classes11.js:1453:134)
    at Bhf (https://g.eags.us/eaglercraft/classes11.js:68:395)
    at Bxt (https://g.eags.us/eaglercraft/classes11.js:67:184)
    at TeaVMThread.runner (https://g.eags.us/eaglercraft/classes11.js:23:404)
    at TeaVMThread.run (https://g.eags.us/eaglercraft/classes11.js:15824:111)
    at TeaVMThread.resume (https://g.eags.us/eaglercraft/classes11.js:15824:9)

eaglercraft.version = "22w04b"
eaglercraft.minecraft = "1.5.2"
eaglercraft.brand = "eagtek"
eaglercraft.username = "antgame11"
eaglercraft.channel = "EaglerDeev71_487"

window.minecraftOpts = ["game_frame","assets.epk"]

window.navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 6
window.navigator.deviceMemory = 8
window.navigator.platform = Win32
window.navigator.product = Gecko

rootElement.clientWidth = 1920
rootElement.clientHeight = 975
window.innerWidth = 1920
window.innerHeight = 975
window.outerWidth = 1920
window.outerHeight = 1080
window.devicePixelRatio = 1
window.screen.availWidth = 1920
window.screen.availHeight = 1080
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.currentContext = [object WebGL2RenderingContext]

window.location.href = https://g.eags.us/eaglercraft/game.html
window.location.ancestorOrigins = {}

----- Begin Minecraft Config -----
CgAAAwAIa2V5Lnpvb20AAAAuAwAMa2V5LnBpY2tJdGVt////ngEAD2NoYXRMaW5rc1Byb21wdAEDAAxrZXkuZnVuY3Rpb24AAAAhAwAIa2V5LmNoYXQAAAAUAwAKa2V5LnNwcmludAAAABMFAAtzb3VuZFZvbHVtZT+AAAABABBwYXRjaEFuaXNvdHJvcGljAQMADmNoYXRWaXNpYmlsaXR5AAAAAAMADWtleS5pbnZlbnRvcnkAAAASAQARaGlkZVNlcnZlckFkZHJlc3MACQAHc2VydmVycwoAAAADAQALaGlkZUFkZHJlc3MACAACaXAAGndzczovL21jLnByaW1pdHQudGsvc2VydmVyCAAEbmFtZQAQTWluZWNyYWZ0IFNlcnZlcgABAAtoaWRlQWRkcmVzcwAIAAJpcAAhd3NzOi8vOTRiZi03My00NC0xMDEtMjIzLm5ncm9rLmlvCAAEbmFtZQAQTWluZWNyYWZ0IFNlcnZlcgABAAtoaWRlQWRkcmVzcwAIAAJpcAAbd3NzOi8vcy5jdW0uc29mdHdhcmUvc2VydmVyCAAEbmFtZQAQTWluZWNyYWZ0IFNlcnZlcgABAAt2aWV3Qm9iYmluZwEBABBhZHZhbmNlZFRvb2x0aXBzAAUAC2NoYXRPcGFjaXR5P4AAAAMACGtleS5iYWNrAAAAHwMACmZvcmNlV2lkdGgAAAAAAwAIa2V5LmRyb3AAAAAQAQAQcGF1c2VPbkxvc3RGb2N1cwEFAAtzZW5zaXRpdml0eT8AAAAFAAttdXNpY1ZvbHVtZQAAAAAFAAVnYW1tYT+AAAADAAlwYXJ0aWNsZXMAAAAAAQALY2hhdENvbG91cnMBAwALa2V5LmZvcndhcmQAAAARAwAIa2V5LmxlZnQAAAAeAwAKa2V5LmF0dGFja////5wDAAx2aWV3RGlzdGFuY2UAAAABAQADZm9nAQEACWNoYXRMaW5rcwEDAAlrZXkuc25lYWsAAAAqBQADZm92P4AAAAMACWtleS5yaWdodAAAACAFAAljaGF0V2lkdGg/gAAAAwAIZ3VpU2NhbGUAAAADAwAObGltaXRGcmFtZXJhdGUAAAABBQAJY2hhdFNjYWxlP4AAAAEAFHNlZW5BY2tub3dsZWRnZW1lbnRzAQMAEGFtYmllbnRPY2NsdXNpb24AAAAACAAIbGFuZ3VhZ2UABWVuX1VTAQAIYW5hZ2x5cGgAAQAQaGVsZEl0ZW1Ub29sdGlwcwEFABFjaGF0SGVpZ2h0Rm9jdXNlZD+AAAABAApmdWxsU2NyZWVuAAMACGtleS5qdW1wAAAAOQEABmNsb3VkcwAFABNjaGF0SGVpZ2h0VW5mb2N1c2VkPuMnqQEAC3RvdWNoc2NyZWVuAAMADmtleS5wbGF5ZXJsaXN0AAAADwEAC2ludmVydE1vdXNlAAEACHNob3dDYXBlAQMADWFudGlhbGlhc01vZGUAAAABAwALZm9yY2VIZWlnaHQAAAAAAQANZmFuY3lHcmFwaGljcwADAAdrZXkudXNl////nQgACmxhc3RTZXJ2ZXIAAAA=
----- End Minecraft Config -----

window.minecraftServer = wss://s.cum.software/server

**Comment by LAX1DUDE** [comment]
Try this commit [https://github.com/LAX1DUDE/eaglercraft/commit/a4aab640d7092a2385ccdba58dabfeefe751c0da](https://github.com/LAX1DUDE/eaglercraft/commit/a4aab640d7092a2385ccdba58dabfeefe751c0da)

I'll assume it's fixed and close this if nobody else reports this crash again for a good week or two

**Comment by LAX1DUDE** [comment]
I tried to patch it again [https://github.com/LAX1DUDE/eaglercraft/commit/081dd6ce3f94a6a2678d2626e0c98470a3414ac7](https://github.com/LAX1DUDE/eaglercraft/commit/081dd6ce3f94a6a2678d2626e0c98470a3414ac7)
