### ISSUE TITLE
It keep on crashing

### ISSUE THREAD

**Issue by CyberhackerYT** [LAX1DUDE/eaglercraft#135]
Game Crashed! I have fallen and I can't get up! If this has happened more than once then please copy the text on this screen and publish it in the issues feed of this fork's GitHub repository.

The URL to this fork's GitHub repository is: https://github.com/LAX1DUDE/eaglercraft

Native Browser Exception
----------------------------------
  Line: 15824:393
  Type: Error
  Message: Java exception thrown
----------------------------------

Error: Java exception thrown
    at $rt_exception (https://firealt.ubunto.repl.co/classes.js:10:390)
    at $rt_throw (https://firealt.ubunto.repl.co/classes.js:10:218)
    at AQs (https://firealt.ubunto.repl.co/classes.js:11981:144)
    at X5 (https://firealt.ubunto.repl.co/classes.js:11979:33)
    at A70 (https://firealt.ubunto.repl.co/classes.js:13677:231)
    at YI.$rt_array.toString [as k5] (https://firealt.ubunto.repl.co/classes.js:15631:268)
    at Bi0 (https://firealt.ubunto.repl.co/classes.js:1505:117)
    at A8N (https://firealt.ubunto.repl.co/classes.js:1458:44)
    at Bun (https://firealt.ubunto.repl.co/classes.js:1453:134)
    at Bhe (https://firealt.ubunto.repl.co/classes.js:68:395)

eaglercraft.version = "22w07a"
eaglercraft.minecraft = "1.5.2"
eaglercraft.brand = "eagtek"
eaglercraft.username = "PriemumIvy_"
eaglercraft.channel = "PriemumIvy__154"

window.minecraftOpts = ["game_frame","assets.epk","CgAACQAHc2VydmVycwoAAAABCAAKZm9yY2VkTU9URAAVWW91ciBNaW5lY3JhZnQgU2VydmVyAQALaGlkZUFkZHJlc3MBCAACaXAAI3dzczovL2ZpcmVhbHQudWJ1bnRvLnJlcGwuY28vc2VydmVyCAAEbmFtZQAQTWluZWNyYWZ0IFNlcnZlcgAA"]

window.navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14388.61.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.107 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 2
window.navigator.deviceMemory = 4
window.navigator.platform = Linux x86_64
window.navigator.product = Gecko

rootElement.clientWidth = 1518
rootElement.clientHeight = 750
window.innerWidth = 1517
window.innerHeight = 750
window.outerWidth = 1517
window.outerHeight = 853
window.devicePixelRatio = 0.8999999761581421
window.screen.availWidth = 1517
window.screen.availHeight = 853
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.currentContext = [object WebGL2RenderingContext]

window.location.href = https://firealt.ubunto.repl.co/
window.location.ancestorOrigins = {}

----- Begin Minecraft Config -----
CgAAAwAIa2V5Lnpvb20AAAAuAwAMa2V5LnBpY2tJdGVt////ngEAD2NoYXRMaW5rc1Byb21wdAEDAAxrZXkuZnVuY3Rpb24AAAAhAwAIa2V5LmNoYXQAAAAUAwAKa2V5LnNwcmludAAAABMFAAtzb3VuZFZvbHVtZT+AAAABABBwYXRjaEFuaXNvdHJvcGljAAMADmNoYXRWaXNpYmlsaXR5AAAAAAMADWtleS5pbnZlbnRvcnkAAAASAQARaGlkZVNlcnZlckFkZHJlc3MAAQALdmlld0JvYmJpbmcBAQAQYWR2YW5jZWRUb29sdGlwcwAFAAtjaGF0T3BhY2l0eT+AAAADAAhrZXkuYmFjawAAAB8DAApmb3JjZVdpZHRoAAAAAAMACGtleS5kcm9wAAAAEAEAEHBhdXNlT25Mb3N0Rm9jdXMBBQALc2Vuc2l0aXZpdHk/AAAABQALbXVzaWNWb2x1bWUAAAAABQAFZ2FtbWE/gAAAAwAJcGFydGljbGVzAAAAAAEAC2NoYXRDb2xvdXJzAQMACGtleS5sZWZ0AAAAHgMAC2tleS5mb3J3YXJkAAAAEQMACmtleS5hdHRhY2v///+cAwAMdmlld0Rpc3RhbmNlAAAAAQEAA2ZvZwEBAAljaGF0TGlua3MBAwAJa2V5LnNuZWFrAAAAKgUAA2Zvdj8Xb8YDAAlrZXkucmlnaHQAAAAgBQAJY2hhdFdpZHRoP4AAAAMACGd1aVNjYWxlAAAAAwMADmxpbWl0RnJhbWVyYXRlAAAAAQUACWNoYXRTY2FsZT+AAAABABRzZWVuQWNrbm93bGVkZ2VtZW50cwEDABBhbWJpZW50T2NjbHVzaW9uAAAAAAgACGxhbmd1YWdlAAVlbl9VUwEACGFuYWdseXBoAAEAEGhlbGRJdGVtVG9vbHRpcHMBBQARY2hhdEhlaWdodEZvY3VzZWQ/gAAAAQAKZnVsbFNjcmVlbgADAAhrZXkuanVtcAAAADkBAAZjbG91ZHMABQATY2hhdEhlaWdodFVuZm9jdXNlZD7jJ6kBAAt0b3VjaHNjcmVlbgADAA5rZXkucGxheWVybGlzdAAAAA8BAAtpbnZlcnRNb3VzZQABAAhzaG93Q2FwZQEDAA1hbnRpYWxpYXNNb2RlAAAAAQMAC2ZvcmNlSGVpZ2h0AAAAAAEADWZhbmN5R3JhcGhpY3MAAwAHa2V5LnVzZf///50IAApsYXN0U2VydmVyAAAA
----- End Minecraft Config -----

window.minecraftServer = wss://firealt.ubunto.repl.co/server

**Comment by LAX1DUDE** [comment]
> Error: Java exception thrown at $rt_exception (https://firealt.ubunto.repl.co/classes.js:10:390)
> at $rt_throw (https://firealt.ubunto.repl.co/classes.js:10:218)
> at AQs (https://firealt.ubunto.repl.co/classes.js:11981:144)
> at X5 (https://firealt.ubunto.repl.co/classes.js:11979:33)
> at A70 (https://firealt.ubunto.repl.co/classes.js:13677:231)
> at YI.$rt_array.toString [as k5] (https://firealt.ubunto.repl.co/classes.js:15631:268)
> at Bi0 (https://firealt.ubunto.repl.co/classes.js:1505:117)
> at A8N (https://firealt.ubunto.repl.co/classes.js:1458:44) 
> at Bun (https://firealt.ubunto.repl.co/classes.js:1453:134)
> at Bhe (https://firealt.ubunto.repl.co/classes.js:68:395)

I decoded this and found that this crash is because you are trying to overflow a part of the minecraft packet deserialization code on the server you are joining by loading a malicious skin, and the client is blocking your skin by crashing the game before you nuke the server

I suggest you 'Clear List' on the profile screen and use a preset skin instead, I'll keep this open as a reminder to myself to patch this code to automatically kick and delete malicious skins instead of crashing the whole game to make it less interesting
